// THE STUDY, part 3: try to break it.
//
// Every figure in research/RESULTS.md rests on modelling choices. This script
// re-derives the results a second way and then changes the choices one at a
// time to see how much each one matters. It reads the flights written by
// research/run.ts and the candles, and writes research/AUDIT.md.
//
//   tsx research/audit.ts

import fs from 'node:fs';
import path from 'node:path';
import { earningsCalendar } from '../src/core/earnings';
import { takeoff } from '../src/core/flight';
import { INSTRUMENTS } from '../src/core/market';
import { Candle, Flight, FlightPlan, MarketState } from '../src/core/types';
import { DAY, HOUR } from '../src/core/util';
import { tickFlight } from '../src/core/watchman';
import { LOOKBACK_H, mean, studyMarket } from './lib';
import { MARGIN, SCENARIOS, Scenario, Trade, WARM_UP_H } from './run';

const here = path.dirname(process.argv[1]);
const full = studyMarket();
const pct = (x: number, dp = 1) => (Number.isFinite(x) ? (x * 100).toFixed(dp) + '%' : 'n/a');
const usd = (x: number) => (x < 0 ? '-' : '') + Math.abs(x).toFixed(2);
const int = (x: number) => x.toLocaleString('en-US');
const table = (head: string[], rows: (string | number)[][]) =>
  [`| ${head.join(' | ')} |`, `| ${head.map((_, i) => (i ? '---:' : '---')).join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`)].join('\n');
const share = <T>(xs: T[], f: (x: T) => boolean) => (xs.length ? xs.filter(f).length / xs.length : NaN);
const load = (sc: string): Trade[] => Object.keys(INSTRUMENTS).flatMap((s) => JSON.parse(fs.readFileSync(path.join(here, 'out', `${sc}-${s}.json`), 'utf8')) as Trade[]);
const liqA = (t: Trade) => t.a[1] === 'liquidated';
const index = Object.fromEntries(Object.keys(INSTRUMENTS).map((s) => [s, new Map(full.hourly[s].map((b, i) => [b.t, i]))]));

interface Opt { mmr?: number; liqNearer?: number; liqFirst?: boolean }

/**
 * A second, independent implementation of "fly the plan as filed": thirty
 * lines that share no code with src/core/flight.ts. If the two disagree on any
 * plan, one of them is wrong.
 */
function flyPlain(sc: Scenario, t: Trade, lev: number, opt: Opt = {}): [number, string, boolean] {
  const inst = INSTRUMENTS[t.symbol], bars = full.hourly[t.symbol], i = index[t.symbol].get(t.t) as number;
  const entry = bars[i - 1].c, d = t.side === 'long' ? 1 : -1;
  const round = (x: number) => Number(x.toFixed(inst.pricePlace));
  const liq = entry * (1 - d * (1 / lev - (opt.mmr ?? inst.mmr) - (opt.liqNearer ?? 0)));
  let stop = sc.stopPct === undefined ? undefined : round(entry * (1 - d * sc.stopPct));
  if (stop !== undefined && (stop - liq) * d <= 0) stop = undefined; // a stop beyond liquidation can never fill
  const target = sc.targetPct === undefined ? undefined : round(entry * (1 + d * sc.targetPct));
  const qty = (MARGIN * lev) / entry, fees = MARGIN * lev * inst.takerFee * 2, slip = inst.cls === 'rwa' ? 0.002 : 0.001;
  for (let j = i; j < i + sc.horizonH; j++) {
    const b = bars[j], adverse = d === 1 ? b.l : b.h, favourable = d === 1 ? b.h : b.l;
    const hitLiq = (adverse - liq) * d <= 0;
    if (stop !== undefined && (adverse - stop) * d <= 0) {
      if (opt.liqFirst && hitLiq) return [-MARGIN, 'liquidated', true];
      const fill = ((b.o - stop) * d <= 0 ? b.o : stop) * (1 - d * slip);
      if ((fill - liq) * d <= 0) return [-MARGIN, 'liquidated', hitLiq];
      return [Math.max(-MARGIN, qty * (fill - entry) * d - fees), 'stopped', hitLiq];
    }
    if (hitLiq) return [-MARGIN, 'liquidated', true];
    if (target !== undefined && (favourable - target) * d >= 0) return [Math.max(-MARGIN, qty * (target - entry) * d - fees), 'target', false];
    if (j === i + sc.horizonH - 1) return [Math.max(-MARGIN, qty * (b.c - entry) * d - fees), 'timeout', false];
  }
  throw new Error('unreachable');
}

const md: string[] = ['# Robustness checks', '', 'Generated by `npm run study:audit`. Each section changes one assumption behind research/RESULTS.md, or re-derives a result a second way, and reports how far the answer moves. docs/STUDY.md explains what to make of them.', ''];
const json: Record<string, unknown> = {};
const tests = Object.fromEntries(Object.values(SCENARIOS).map((sc) => [sc.id, load(sc.id)])) as Record<string, Trade[]>;

// 1. the second implementation -----------------------------------------------------
{
  const rows: (string | number)[][] = [];
  const out: Record<string, unknown> = {};
  for (const sc of Object.values(SCENARIOS)) {
    let same = 0, worst = 0;
    for (const t of tests[sc.id]) { const [pnl, outcome] = flyPlain(sc, t, t.lev); const err = Math.abs(pnl - t.a[0]); worst = Math.max(worst, err); if (err < 1e-6 && outcome === t.a[1]) same++; }
    rows.push([sc.label, int(tests[sc.id].length), int(same), worst.toExponential(1)]);
    out[sc.id] = { plans: tests[sc.id].length, identical: same, largestDifference: worst };
  }
  md.push('## 1. A second implementation of the flight', '', 'The as-filed result of every plan, recomputed from the candles by a separate thirty-line function in this file that shares no code with `src/core/flight.ts`.', '', table(['Test', 'Plans', 'Identical result and outcome', 'Largest difference, USDT'], rows), '');
  json.secondImplementation = out;
}

// 2. how much history the engines had ------------------------------------------------
{
  const n = full.hourly.NVDAUSDT.length - WARM_UP_H - 24 + 1;
  const short = Math.max(0, LOOKBACK_H - WARM_UP_H);
  md.push('## 2. How much history the engines had', '', `The live app asks Bitget for ${LOOKBACK_H} hourly bars. The study starts entering after ${WARM_UP_H}, so the first ${int(Math.min(short, n))} of ${int(n)} entry hours (${pct(Math.min(short, n) / n, 0)}) gave the engines between ${WARM_UP_H} and ${LOOKBACK_H - 1} hourly bars, and the rest the full ${LOOKBACK_H}.`, '');
  json.history = { entryHours: n, withFewerThan500: Math.min(short, n) };
}

// 3. the three tests overlap -----------------------------------------------------------
{
  const key = (t: Trade) => `${t.symbol}|${t.t}|${t.side}|${t.lev}`;
  const all = Object.values(tests).flat().filter(liqA);
  const distinct = new Set(all.map(key));
  const day50 = new Set(tests.day.filter((t) => t.lev === 50 && liqA(t)).map(key)), naked50 = new Set(tests.naked.filter((t) => t.lev === 50 && liqA(t)).map(key));
  const both = [...day50].filter((k) => naked50.has(k)).length;
  md.push('## 3. The three tests are not independent', '', `They use the same hours and contracts. At 50x a stop 2.5% away lies beyond the liquidation price and can never fill, so a 50x plan in the Day test and in the Naked test is the same position as filed: ${int(both)} of the ${int(day50.size)} Day liquidations at 50x are the same events as Naked ones. The ${int(all.length)} as-filed liquidations summed over the three tests are ${int(distinct.size)} distinct positions (contract, hour, side, leverage).`, '');
  json.overlap = { liquidationsSummed: all.length, distinctPositions: distinct.size, day50AlsoInNaked: both };
}

// 4. stop or liquidation first, inside one hour ------------------------------------------
{
  const rows: (string | number)[][] = [];
  const out: Record<string, unknown> = {};
  for (const id of ['day', 'swing']) {
    const sc = SCENARIOS[id];
    for (const lev of [10, 20]) {
      const g = tests[id].filter((t) => t.lev === lev);
      const stopped = g.filter((t) => t.a[1] === 'stopped');
      const ambiguous = stopped.filter((t) => flyPlain(sc, t, lev)[2]).length;
      rows.push([`${sc.label}, ${lev}x`, int(g.length), int(stopped.length), int(ambiguous), pct(ambiguous / g.length)]);
      out[`${id}-${lev}x`] = { plans: g.length, stopped: stopped.length, sameBarAsLiquidation: ambiguous, ceiling: ambiguous / g.length };
    }
  }
  md.push('## 4. Which came first inside the hour: the stop or liquidation?', '', 'Hourly bars do not say in what order prices were hit. The flight model tests the stop first. This counts the stop-outs where the same hourly bar also traded through the liquidation price; if every one of them had in truth been a liquidation, the rate would be the last column instead of zero.', '', table(['Plans as filed', 'Plans', 'Stopped out', 'Stop bar also reached liquidation', 'Liquidation rate if all of those were liquidations'], rows), '');
  json.intrabar = out;
}

// 5. liquidation price with the closing fee -------------------------------------------------
{
  const rows: (string | number)[][] = [];
  const out: Record<string, unknown> = {};
  for (const id of ['day', 'swing']) {
    const sc = SCENARIOS[id], g = tests[id].filter((t) => t.lev === 50);
    const base = share(g, liqA), adj = share(g, (t) => flyPlain(sc, t, 50, { liqNearer: INSTRUMENTS[t.symbol].takerFee })[1] === 'liquidated');
    rows.push([`${sc.label}, 50x`, int(g.length), pct(base), pct(adj), pct(mean(g.map((t) => t.mcLiq)))]);
    out[id] = { base, withFee: adj, forecast: mean(g.map((t) => t.mcLiq)) };
  }
  md.push('## 5. A liquidation price that allows for the closing fee', '', 'The engines put the liquidation price where margin less maintenance margin is used up, ignoring the fee to close. Moving it nearer by one taker fee (0.06%):', '', table(['Plans as filed', 'Plans', 'Liquidated, as modelled', 'Liquidated, fee included', 'Preflight forecast (average)'], rows), '');
  json.liquidationFee = out;
}

// 6. MSTR and COIN, and their assumed maintenance margin ---------------------------------------
{
  const sc = SCENARIOS.naked, g = tests.naked;
  const rows: (string | number)[][] = [];
  const out: Record<string, unknown> = {};
  for (const lev of [10, 20]) {
    const liq = g.filter((t) => t.lev === lev && liqA(t));
    const mc = liq.filter((t) => t.symbol === 'MSTRUSDT' || t.symbol === 'COINUSDT').length;
    const assumed = g.filter((t) => t.lev === lev && INSTRUMENTS[t.symbol].mmr === 0.01);
    const at1 = share(assumed, liqA), atHalf = share(assumed, (t) => flyPlain(sc, t, lev, { mmr: 0.005 })[1] === 'liquidated');
    rows.push([`No stop, ${lev}x`, int(liq.length), int(mc), pct(mc / liq.length, 0), pct(at1), pct(atHalf)]);
    out[`${lev}x`] = { liquidations: liq.length, mstrCoin: mc, assumedContractsAt1pct: at1, assumedContractsAtHalfPct: atHalf };
  }
  md.push('## 6. Where the liquidations below 50x came from', '', 'Maintenance margin was recorded from Bitget for NVDA and BTC. For MSTR, COIN and QQQ it is an assumed 1%. Those are also the most volatile contracts in the set.', '', table(['Plans as filed', 'Liquidations', 'On MSTR or COIN', 'Share', 'Rate on the three assumed-margin contracts, at 1%', 'Same, at 0.5%'], rows), '');
  json.assumedMargin = out;
}

// 7. is the forecast more than a base rate? ---------------------------------------------------------
{
  const rows: (string | number)[][] = [];
  const out: Record<string, unknown> = {};
  const corr = (x: number[], y: number[]) => { const mx = mean(x), my = mean(y); let a = 0, b = 0, c = 0; for (let i = 0; i < x.length; i++) { a += (x[i] - mx) * (y[i] - my); b += (x[i] - mx) ** 2; c += (y[i] - my) ** 2; } return a / Math.sqrt(b * c); };
  for (const [id, lev] of [['day', 50], ['swing', 50], ['naked', 10], ['naked', 20], ['naked', 50]] as [string, number][]) {
    const g = tests[id].filter((t) => t.lev === lev), y = g.map((t) => (liqA(t) ? 1 : 0)), base = mean(y);
    const brier = mean(g.map((t, i) => (t.mcLiq - y[i]) ** 2)), constant = base * (1 - base);
    const bySym = new Map<string, number[]>();
    g.forEach((t, i) => { if (!bySym.has(t.symbol)) bySym.set(t.symbol, []); bySym.get(t.symbol)!.push(y[i]); });
    const perContract = mean(g.map((t, i) => (mean(bySym.get(t.symbol) as number[]) - y[i]) ** 2));
    const byDay = new Map<number, { f: number[]; y: number[] }>();
    g.forEach((t, i) => { const k = Math.floor(t.t / DAY); if (!byDay.has(k)) byDay.set(k, { f: [], y: [] }); byDay.get(k)!.f.push(t.mcLiq); byDay.get(k)!.y.push(y[i]); });
    const F = [...byDay.values()].map((v) => mean(v.f)), Y = [...byDay.values()].map((v) => mean(v.y));
    const groups = new Map<string, { f: number[]; y: number[] }>();
    g.forEach((t, i) => { const k = `${t.symbol}|${t.side}`; if (!groups.has(k)) groups.set(k, { f: [], y: [] }); groups.get(k)!.f.push(t.mcLiq); groups.get(k)!.y.push(y[i]); });
    const errs = [...groups.values()].map((v) => mean(v.f) - mean(v.y));
    rows.push([`${SCENARIOS[id].label}, ${lev}x`, pct(base), pct(mean(g.map((t) => t.mcLiq))), pct(1 - brier / constant, 0), pct(1 - brier / perContract, 0), `${pct(Math.min(...F), 0)} to ${pct(Math.max(...F), 0)}`, `${pct(Math.min(...Y), 0)} to ${pct(Math.max(...Y), 0)}`, corr(F, Y).toFixed(2), `${(Math.min(...errs) * 100).toFixed(0)} to +${(Math.max(...errs) * 100).toFixed(0)} points`]);
    out[`${id}-${lev}x`] = { baseRate: base, forecast: mean(g.map((t) => t.mcLiq)), skillVsConstant: 1 - brier / constant, skillVsPerContractConstant: 1 - brier / perContract, dayForecastRange: [Math.min(...F), Math.max(...F)], dayOutcomeRange: [Math.min(...Y), Math.max(...Y)], dayCorrelation: corr(F, Y), groupErrorRange: [Math.min(...errs), Math.max(...errs)] };
  }
  md.push('## 7. Is the forecast more than a base rate?', '', 'Holding the test and the leverage fixed. "Skill" is the Brier score\'s improvement over a forecast that says the same number for every plan: first one number for the whole group, then one number per contract (that second one is fitted to the outcomes, so it is the best a contract label could do). The day columns compare the average forecast on each entry day with the share liquidated that day.', '', table(['Plans as filed', 'Liquidated', 'Forecast (average)', 'Skill over one constant', 'Skill over a constant per contract', 'Forecast, range by entry day', 'Liquidated, range by entry day', 'Correlation by day', 'Forecast minus outcome, range by contract and side'], rows), '');
  json.forecast = out;
}

// 8. the gap check --------------------------------------------------------------------------------------
{
  const g = tests.day;
  const rows = [10, 20, 50].map((lev) => { const q = g.filter((t) => t.lev === lev), f = q.filter((t) => t.fails.includes('gap')); return [`${lev}x`, int(q.length), int(f.length), pct(f.length / q.length), int(f.filter(liqA).length)]; });
  md.push('## 8. What the gap check cost, and what it caught', '', 'Default stop and target, 24-hour hold.', '', table(['Filed leverage', 'Plans', 'Failed the gap check', 'Share', 'Of those, liquidated as filed'], rows), '');
  json.gapCheck = Object.fromEntries([10, 20, 50].map((lev) => { const q = g.filter((t) => t.lev === lev), f = q.filter((t) => t.fails.includes('gap')); return [`${lev}x`, { plans: q.length, failed: f.length, liquidated: f.filter(liqA).length }]; }));
}

// 9. is zero liquidations the stop or the leverage? ----------------------------------------------------------
{
  const sc = SCENARIOS.naked;
  const flown = tests.naked.filter((t) => t.b);
  const without = flown.filter((t) => flyPlain(sc, t, t.bLev)[1] === 'liquidated').length;
  const asFiledStopped = [...tests.day, ...tests.swing].filter((t) => t.lev <= 20);
  md.push('## 9. Is "no re-routed flight was liquidated" the stop or the leverage?', '', `The leverage. Flying every Naked plan at its re-routed leverage but without the stop the re-route adds, ${int(without)} of ${int(flown.length)} were liquidated. And the default plan as filed at 10x and 20x, with its own stop, had ${int(asFiledStopped.filter(liqA).length)} liquidations in ${int(asFiledStopped.length)} (subject to section 4). In this sample, staying at or under about 12x was enough to avoid liquidation on its own.`, '');
  json.zeroLiquidations = { reroutedLeverageNoStop: without, of: flown.length };
}

// 10. Night Watch with slippage on its own fills ----------------------------------------------------------------
{
  const rows: (string | number)[][] = [];
  const out: Record<string, unknown> = {};
  for (const sc of Object.values(SCENARIOS)) {
    let acted = 0, mismatch = 0, slipSum = 0, diffSum = 0;
    const actions: Record<string, number> = {};
    for (const t of tests[sc.id]) {
      if (!t.b || !t.c || !t.acted) continue;
      const inst = INSTRUMENTS[t.symbol], bars = full.hourly[t.symbol], i = index[t.symbol].get(t.t) as number;
      const entry = bars[i - 1].c, d = t.side === 'long' ? 1 : -1;
      const px = (p: number | undefined, dir: number) => (p === undefined ? undefined : Number((entry * (1 + dir * p)).toFixed(inst.pricePlace)));
      // the stop the re-route added sits one normal move from entry; the runway stored with the plan gives that move back
      const stop = t.bStopAdded ? Number((entry * (1 - d * Math.max((1 / t.lev - inst.mmr) / t.runway, 0.005))).toFixed(inst.pricePlace)) : px(sc.stopPct, -d);
      const plan: FlightPlan = { symbol: t.symbol, side: t.side, leverage: t.bLev, margin: t.bMargin, entry, stop, target: px(sc.targetPct, d), horizonH: sc.horizonH, origin: 'pilot' };
      const air: MarketState = { ...full, hourly: { [t.symbol]: bars.slice(Math.max(0, i - 200), i + sc.horizonH) as Candle[] }, earnings: earningsCalendar(t.t) };
      const f: Flight = tickFlight({ ...takeoff(plan, inst, t.t), watch: true }, air, t.t + sc.horizonH * HOUR, 0).flight;
      if (Math.abs((f.pnl as number) - t.c[0]) > 1e-6) { mismatch++; continue; }
      acted++;
      let open = 1, slip = 0;
      for (const e of f.watchLog ?? []) {
        actions[`${e.rule}: ${e.action}`] = (actions[`${e.rule}: ${e.action}`] ?? 0) + 1;
        const closing = e.action === 'cut-half' ? open * 0.5 : e.action === 'land' ? open : 0;
        slip += closing * plan.margin * plan.leverage * (inst.cls === 'rwa' ? 0.002 : 0.001);
        open -= closing;
      }
      slipSum += slip; diffSum += t.c[0] - t.b[0];
    }
    rows.push([sc.label, int(acted), usd(diffSum / acted), usd(slipSum / acted), usd((diffSum - slipSum) / acted), Object.entries(actions).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${int(v)}`).join('; ')]);
    out[sc.id] = { acted, notReproduced: mismatch, meanDifference: diffSum / acted, slippagePerFlight: slipSum / acted, meanDifferenceWithSlippage: (diffSum - slipSum) / acted, actions };
  }
  md.push('## 10. Night Watch, charged slippage on its own exits', '', 'The flight model fills Night Watch\'s cuts and landings at the close of the hourly bar it has just seen, with no slippage, while a stop pays 0.2% (0.1% on BTC). Charging Night Watch the same on every cut and landing:', '', table(['Test', 'Flights it acted on', 'Mean difference, watch on minus off', 'Slippage not charged, per flight', 'Mean difference with it charged', 'What it did'], rows), '', 'Its runway alarm and its earnings rule never fired in this sample.', '');
  json.nightWatch = out;
}

fs.writeFileSync(path.join(here, 'AUDIT.md'), md.join('\n') + '\n');
fs.writeFileSync(path.join(here, 'audit.json'), JSON.stringify(json, null, 1) + '\n');
console.log(md.join('\n'));
